{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "vp4jhpidxjnan"
  },
  "info": {
    "title": "User Applications API",
    "description": "API calls to work with User applications functionalit.",
    "version": "1.0.0",
    "contact": {
      "name": "API Support",
      "email": "support@navixy.com",
      "url": "https://www.navixy.com/contact/"
    },
    "license": {
      "name": "Apache 2.0",
      "identifier": "Apache-2.0"
    }
  },
  "externalDocs": {
    "description": "Find more info here",
    "url": "https://example.com/docs"
  },
  "servers": [
    {
      "url": "https://api.eu.navixy.com/v2",
      "description": "Navixy production server on European platform"
    },
    {
      "url": "https://api.us.navixy.com/v2",
      "description": "Navixy production server on American platform"
    }
  ],
  "security": [
    {
      "api_key": []
    }
  ],
  "tags": [
    {
      "name": "apps",
      "description": "API for user applications"
    }
  ],
  "paths": {
    "/user/application/list": {
      "get": {
        "tags": [
          "apps"
        ],
        "summary": "Lists all existing user applications",
        "description": "Lists all applications existing in a user account.",
        "operationId": "user_applications_list",
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApplicationListResponse"
                },
                "examples": {
                  "success": {
                    "summary": "Successful response",
                    "value": {
                      "success": true,
                      "list": [
                        {
                          "id": 221,
                          "label": "An application",
                          "url_template": "https://domain.example/{language}",
                          "enabled": true,
                          "authorization": {
                            "type": "user_session"
                          },
                          "display_method": "new_tab",
                          "icon": "extension",
                          "description": "A description"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "kr440w4g07wcc"
        }
      }
    },
    "/user/application/create": {
      "post": {
        "tags": [
          "apps"
        ],
        "summary": "Creates a new application",
        "description": "Creates a new application.",
        "operationId": "user_applications_create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "application": {
                    "$ref": "#/components/schemas/CreateApplicationRequest"
                  }
                },
                "required": [
                  "application"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateApplicationResponse"
                },
                "examples": {
                  "success": {
                    "summary": "Successful response",
                    "value": {
                      "success": true,
                      "id": 779
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "o8zxa2uvzswzy"
        }
      }
    },
    "/user/application/update": {
      "put": {
        "tags": [
          "apps"
        ],
        "summary": "Updates an existing application",
        "description": "Updates an existing application.",
        "operationId": "user_applications_update",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "application": {
                    "$ref": "#/components/schemas/Application"
                  }
                },
                "required": [
                  "application"
                ]
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "success": {
                    "summary": "Successful response",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Application not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "error": {
                    "summary": "Error response",
                    "value": {
                      "success": false,
                      "error": {
                        "code": 201,
                        "message": "Application not found"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "ilzydm36ofosu"
        }
      }
    },
    "/user/application/delete": {
      "delete": {
        "tags": [
          "apps"
        ],
        "summary": "Deletes a specified application by its unique identifier",
        "description": "Deletes a specified application by its unique identifier.",
        "operationId": "user_applications_delete",
        "parameters": [
          {
            "name": "application_id",
            "in": "query",
            "description": "Application's id to delete.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "success": {
                    "summary": "Successful response",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Application not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "error": {
                    "summary": "Error response",
                    "value": {
                      "success": false,
                      "error": {
                        "code": 201,
                        "message": "Application not found"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "llenypsrnuw27"
        }
      }
    },
    "/user/application/enabled/set": {
      "post": {
        "tags": [
          "apps"
        ],
        "summary": "Toggles application visibility in the side menu",
        "description": "Toggles application visibility in the side menu.",
        "operationId": "user_applications_enabled_set",
        "parameters": [
          {
            "name": "application_id",
            "in": "query",
            "description": "Application's id to update.",
            "required": true,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "enabled",
            "in": "query",
            "description": "State to set.",
            "required": true,
            "schema": {
              "type": "boolean"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SuccessResponse"
                },
                "examples": {
                  "success": {
                    "summary": "Successful response",
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Application not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "examples": {
                  "error": {
                    "summary": "Error response",
                    "value": {
                      "success": false,
                      "error": {
                        "code": 201,
                        "message": "Application not found"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "w31x2duj9kqct"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SuccessResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "description": "Operation success status",
            "example": true
          }
        },
        "x-stoplight": {
          "id": "g640237nnbne1"
        }
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "description": "Operation failed status",
            "example": false
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "integer",
                "description": "Error code",
                "example": 201
              },
              "message": {
                "type": "string",
                "description": "Error message",
                "example": "Application not found"
              }
            }
          }
        },
        "x-stoplight": {
          "id": "2lzs7tcs6qu55"
        }
      },
      "ApiKeyAuthorization": {
        "type": "object",
        "required": [
          "type",
          "hash"
        ],
        "properties": {
          "type": {
            "type": "string",
            "description": "Authorization type identifier",
            "enum": [
              "api_key"
            ]
          },
          "hash": {
            "type": "string",
            "description": "An API key hash"
          }
        },
        "x-stoplight": {
          "id": "dew9jd7cc834m"
        }
      },
      "UserSessionAuthorization": {
        "type": "object",
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "type": "string",
            "description": "Authorization type identifier",
            "enum": [
              "user_session"
            ]
          }
        },
        "x-stoplight": {
          "id": "jv0toy3i2mlox"
        }
      },
      "ApplicationAuthorization": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/ApiKeyAuthorization"
          },
          {
            "$ref": "#/components/schemas/UserSessionAuthorization"
          }
        ],
        "x-stoplight": {
          "id": "okbksxujz77se"
        }
      },
      "Application": {
        "type": "object",
        "required": [
          "id",
          "label",
          "url_template"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "description": "Application's ID"
          },
          "label": {
            "type": "string",
            "description": "Application's name"
          },
          "url_template": {
            "type": "string",
            "description": "URL template (including variables)"
          },
          "enabled": {
            "type": "boolean",
            "description": "Determines visibility in the users' side menu",
            "default": true
          },
          "authorization": {
            "$ref": "#/components/schemas/ApplicationAuthorization",
            "description": "Authorization that will be used while accessing the URL"
          },
          "display_method": {
            "type": "string",
            "description": "Determines how the application will be opened",
            "enum": [
              "new_tab",
              "embedded"
            ],
            "default": "new_tab"
          },
          "icon": {
            "type": "string",
            "description": "Application's icon identifier",
            "default": "extension"
          },
          "description": {
            "type": "string",
            "description": "Longer plain text description is shown to users",
            "default": ""
          }
        },
        "x-stoplight": {
          "id": "3sm7m3q782lw0"
        }
      },
      "CreateApplicationRequest": {
        "type": "object",
        "required": [
          "label",
          "url_template"
        ],
        "properties": {
          "label": {
            "type": "string",
            "description": "Application's name"
          },
          "url_template": {
            "type": "string",
            "description": "URL template (including variables)"
          },
          "authorization": {
            "$ref": "#/components/schemas/ApplicationAuthorization",
            "description": "Authorization that will be used while accessing the URL"
          },
          "display_method": {
            "type": "string",
            "description": "Determines how the application will be opened",
            "enum": [
              "new_tab",
              "embedded"
            ],
            "default": "new_tab"
          },
          "icon": {
            "type": "string",
            "description": "Application's icon identifier",
            "default": "extension"
          },
          "description": {
            "type": "string",
            "description": "Longer plain text description is shown to users",
            "default": ""
          }
        },
        "x-stoplight": {
          "id": "x8of5ltmir60c"
        }
      },
      "ApplicationListResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "description": "Operation success status",
            "example": true
          },
          "list": {
            "type": "array",
            "description": "List of applications",
            "items": {
              "$ref": "#/components/schemas/Application"
            }
          }
        },
        "x-stoplight": {
          "id": "eq0wd15gdr4dn"
        }
      },
      "CreateApplicationResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "description": "Operation success status",
            "example": true
          },
          "id": {
            "type": "integer",
            "description": "Unique ID of the created application",
            "example": 779
          }
        },
        "x-stoplight": {
          "id": "7uj730lvv7vw4"
        }
      }
    },
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "api_key",
        "in": "header",
        "description": "API key authentication"
      }
    },
    "responses": {
      "Success": {
        "description": "Successful response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SuccessResponse"
            }
          }
        }
      },
      "Error": {
        "description": "Error response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ErrorResponse"
            }
          }
        }
      }
    }
  }
}